config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "users/:id/profile", to: "users#edit", as: "profile"
  patch "users/:id", to: "users#renewal", as: "profile_renewal"

  get 'pages/index'
  root to: "pages#index"

  resources :hotels

  resources :bookings do
    collection do
      post :confirm, action: :confirm
      post :back, action: :back
      post :complete, action: :complete
    end
  end

  resources :bookings

  resources :pages do
    collection do
      get "search"
    end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :booking_hotels
  has_many :hotels, through: :booking_hotels

  has_many :booking_users
  has_many :users, through: :booking_users

  validate :start_end_check
  def start_end_check
    if start_date.nil?
      errors.add(:start_date, "を入力してください。")
    elsif end_date.nil?
      errors.add(:end_date, "を入力してください。")
    elsif end_date < start_date
      errors.add(:end_date, "は開始日より前の日付は登録できません。")
    end
  end

  validate :start_before_today
  def start_before_today
    errors.add(:start_date, "は今日より前の日付は登録できません。") if start_date.nil? || start_date < Date.today
  end


  validates :person_num, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  def confirm
    @booking = Booking.new(booking_params)
    session[:booking] = @booking

    @hotel = Hotel.find(@booking.hotel_id)

    if @booking.invalid?
      render template: "hotels/show"
    else
      @stay_days = (@booking.end_date.to_date - @booking.start_date.to_date).to_i
      @sum_price = @hotel.price * @booking.person_num
    end
  end

  def complete
    @booking = Booking.new(session[:booking])

    if @booking.save
      session.delete(:booking)
      redirect_to booking_path(@booking.id)
    else
      render "new"
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @hotel = Hotel.find(@booking.hotel_id)
    @sum_price = @hotel.price * @booking.person_num
    flash[:notice] = "ご予約ありがとうございます。 予約が完了しました。"
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    flash[:notice] = "予約をキャンセルしました"
    redirect_to bookings_path
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :person_num, :user_id, :hotel_id)
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/confirm.html.erb
<div class="booking-confirm">
  <h2>予約内容の確認</h2>

  <h3>１泊１人  <%= @hotel.price %>円</h3>

  <div>
    <table>
      <tr>
        <th>開始日</th>
        <td><%= @booking.start_date.to_s(:datetime_jp) %></td>
      </tr>
      <tr>
        <th>終了日</th>
        <td><%= @booking.end_date.to_s(:datetime_jp) %></td>
      </tr>
      <tr>
        <th>宿泊日数</th>
        <td><%= @stay_days %>泊</td>
      </tr>
      <tr>
        <th>人数</th>
        <td><%= @booking.person_num %>人</td>
      </tr>
      <tr>
        <th>ご利用金額合計</th>
        <td><%= @sum_price %>円</td>
      </tr>
    </table>
  </div>

  <%= form_with(model: @booking, url: complete_bookings_path, data: { turbo: false }) do |f| %>
    <input type="button" onclick="submit();" value="予約を確定する" />
  <% end %>

  <%= link_to "戻る", hotel_path(@hotel.id) %>
</div>

app/views/bookings/index.html.erb
<div class="booked-rooms">
  <h2>予約ルームの一覧</h2>

  <table>
    <thead>
      <tr>
        <th>ルームイメージ</th>
        <th>ルーム名</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約人数</th>
        <th>合計料金</th>
        <th>予約した日</th>
        <th>予約のキャンセル</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <% @bookings.each do |booking| %>
          <% @hotels = Hotel.where(id: booking.hotel_id) %>
            <% @hotels.each do |hotel| %>
              <td><%= link_to image_tag(hotel.image), hotel_path(hotel) %></td>
              <td><%= link_to hotel.room_name, hotel_path(hotel), class: "room-name" %></td>
              <td><%= booking.start_date.to_s(:datetime_jp) %></td>
              <td><%= booking.end_date.to_s(:datetime_jp) %></td>
              <td><%= booking.person_num %>名</td>
              <td><%= hotel.price * booking.person_num %> 円</td>
              <td><%= booking.created_at.to_s(:datetime_jp) %></td>
              <%# <><%= booking.user_id
              <%= booking.hotel_id %>
              <td><%= button_to "キャンセル" ,booking_path(booking), method: :delete %></td>
      </tr>
      <tr>
              <td colspan="8" class="booked-room-introduction"><%= hotel.room_introduction %></td>
      </tr>
            <% end %>
        <% end %>
    </tbody>
  </table>
</div>

app/views/bookings/show.html.erb
<div class="booking-complete">
  <h2>予約内容</h2>

  <div class="booking-detail">
    <div class="row">
      <label for="room">予約ルーム</label>
      <div class="content"><%= link_to @hotel.room_name, hotel_path(@hotel) %></div>
    </div>
    <div class="row">
      <label for="start_date">開始日</label>
      <div class="content"><%= @booking.start_date.to_s(:datetime_jp) %></div>
    </div>
    <div class="row">
      <label for="end_date">終了日</label>
      <div class="content"><%= @booking.end_date.to_s(:datetime_jp) %></div>
    </div>
    <div class="row">
      <label for="person-num">人数</label>
      <div class="content"><%= @booking.person_num %> 名</div>
    </div>
    <div class="row">
      <label for="sum_price">ご利用金額合計</label>
      <div class="content"><%= @sum_price %> 円</div>
    </div>
  </div>
</div>