config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "users/:id/profile", to: "users#edit", as: "profile"
  patch "users/:id", to: "users#renewal", as: "profile_renewal"

  get 'pages/index'
  root to: "pages#index"

  resources :hotels

  resources :bookings do
    collection do
      post :confirm, action: :confirm
      post :back, action: :back
      post :complete, action: :complete
    end
  end

  resources :bookings

  resources :pages do
    collection do
      get "search"
    end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :booking_hotels
  has_many :hotels, through: :booking_hotels

  has_many :booking_users
  has_many :users, through: :booking_users

  validate :start_end_check
  def start_end_check
    if start_date.nil?
      errors.add(:start_date, "を入力してください。")
    elsif end_date.nil?
      errors.add(:end_date, "を入力してください。")
    elsif end_date < start_date
      errors.add(:end_date, "は開始日より前の日付は登録できません。")
    end
  end

  validate :start_before_today
  def start_before_today
    errors.add(:start_date, "は今日より前の日付は登録できません。") if start_date.nil? || start_date < Date.today
  end


  validates :person_num, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

end

app/models/booking_hotel.rb
class BookingHotel < ApplicationRecord
  belongs_to :hotel_id
  belongs_to :booking_id
end

app/models/booking_user.rb
class BookingUser < ApplicationRecord
  belongs_to :user
  belongs_to :booking
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :hotel_users
  has_many :users, through: :hotel_users

  has_many :booking_hotels
  has_many :bookings, through: :booking_hotels

  has_one_attached :image

  validates :room_name, :room_introduction, :price, :address, presence: true
  validates :image, presence: { message: 'を選択してください' }
  validates :price,numericality: true
end

app/models/hotel_user.rb
class HotelUser < ApplicationRecord
  belongs_to :hotel_id
  belongs_to :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :introduction, presence: true, on: :renewal
  validates :image, presence: { message: 'を選択してください' }, on: :renewal

  has_many :hotel_users
  has_many :hotels, through: :hotel_users

  has_many :booking_users
  has_many :bookings, through: :booking_users

  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  # ログイン済ユーザーのみにアクセスを許可する
  # before_action :authenticate_user!

  before_action :set_q
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :introduction, :avatar])
  end


  private

  def set_q
    @q = Hotel.ransack(params[:q])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  def confirm
    @booking = Booking.new(booking_params)
    session[:booking] = @booking

    @hotel = Hotel.find(@booking.hotel_id)

    if @booking.invalid?
      render template: "hotels/show"
    else
      @stay_days = (@booking.end_date.to_date - @booking.start_date.to_date).to_i
      @sum_price = @hotel.price * @booking.person_num
    end
  end

  def complete
    @booking = Booking.new(session[:booking])

    if @booking.save
      session.delete(:booking)
      redirect_to booking_path(@booking.id)
    else
      render "new"
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @hotel = Hotel.find(@booking.hotel_id)
    @sum_price = @hotel.price * @booking.person_num
    flash[:notice] = "ご予約ありがとうございます。 予約が完了しました。"
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    flash[:notice] = "予約をキャンセルしました"
    redirect_to bookings_path
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :person_num, :user_id, :hotel_id)
  end

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :move_to_signed_in, only: [:show]

  def index
    @hotels = Hotel.where(user_id: current_user.id)
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(hotel_params)

    if @hotel.save
      flash[:notice] = "ルームを登録しました"
      redirect_to hotel_path(@hotel)
    else
      render "new"
    end
  end

  def show
    if request.referer&.include?(confirm_bookings_path)
      @booking = Booking.new(session[:booking])
      @hotel = Hotel.find(params[:id])
      @user = User.find(@hotel.user_id)
    else
      @booking = Booking.new
      @hotel = Hotel.find(params[:id])
      @user = User.find(@hotel.user_id)
    end
  end

  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy
    flash[:notice] = "ルームを削除しました"
    redirect_to hotels_path
  end


  private

  def hotel_params
    params.require(:hotel).permit(:room_name, :room_introduction, :price, :address, :user_id, :image)
  end

  def move_to_signed_in
    unless user_signed_in?
      #サインインしていないユーザーはログインページが表示される
      redirect_to  '/users/sign_in'
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def index
  end

  def search
    @results = @q.result(distinct: true)

    @count = 0
    @results.each do |result|
        @sum = @count + 1
        @count = @sum
    end
  end

  private

  def set_q
    @q = Hotel.ransack(params[:q])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = current_user
  end

  def renewal
    @user = current_user

    if @user.update(user_params)
      flash[:notice] = "プロフィールを編集しました"
      redirect_to root_path
    else
      render "edit"
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.css"> %>
  </head>

  <body>
    <div class="wrapper">
      <header class="header">
        <div class="header-nav">
          <%= link_to image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png", class:"logo"), root_path %>

          <div class="search">
            <%= search_form_for @q, url: search_pages_path, class: "header-search" do |f| %>
              <%= f.search_field :address_cont, placeholder: "エリア" %>
              <i class="fa fa-map-marker"></i>
            <% end %>
            <%= search_form_for @q, url: search_pages_path, class: "header-search" do |f| %>
              <%= f.search_field :room_name_or_room_introduction_cont, class:"", placeholder: "キーワード"%>
              <i class="fa fa-search"></i>
            <% end %>
          </div>
        </div>

        <div class="header-nav-button">
          <% if user_signed_in? %>
            <div class="header-right-nav">
              <div class="header-username">
                <%= current_user.name %>
              </div>

              <details>
                <summary>
                  <% if current_user.image.attached? %>
                    <%= image_tag current_user.image, size: '50x50'%>
                  <% else %>
                    <p>MENU</p>
                  <% end %>
                </summary>
                <div class="menu-list">
                  <li><%= link_to "ルームの登録", new_hotel_path %></li>
                  <li><%= link_to "予約ルーム一覧", bookings_path %></li>
                  <li><%= link_to "登録ルーム一覧", hotels_path %></li>
                  <li><%= link_to "ユーザー情報の変更", profile_path(current_user.id) %></li>
                  <li><%= button_to "ログアウト", destroy_user_session_path, class: "header-button", method: :delete %></li>
                </div>
              </details>
            </div>

          <% else %>
              <%= link_to "ログイン", new_user_session_path, class: "header-login-button" %>
              <%= link_to "新規登録", new_user_registration_path, class: "header-sign-up-button" %>
          <% end %>

          <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
        </div>
      </header>

      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>

      <%= yield %>

      <footer>© 2022 POTEPAN.INC.</footer>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="top">
  <div class="top-main">
    <h2>Potepan Shareで<br>まだ体験したことのない旅をしよう</h2>
    <div class="top-search">
      <%= search_form_for @q, url: search_pages_path do |f| %>
        <%= f.label :address_cont, "エリア" %><br>
        <%= f.search_field :address_cont, placeholder: " 東京" %>
        <br>
        <%= f.submit "search", class: "search-form-button" %>
      <% end %>
    </div>
  </div>
</div>


<div class="area-panel">
  <div class="area-panel-item">
    <span>東京</span>
    <%= link_to controller: "pages", action: "search", q: { address_cont: "東京"} do %>
      <%= image_tag "https://cdn.pixabay.com/photo/2017/04/01/10/59/tokyo-2193354_960_720.jpg", alt: "search_tokyo", class: "area-panel-image" %>
    <% end %>
  </div>
  <div class="area-panel-item">
  <span>京都</span>
    <%= link_to controller: "pages", action: "search", q: { address_cont: "京都"} do %>
      <%= image_tag "https://images.unsplash.com/photo-1573047330192-4e6bb1594325?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80", alt: "search_kyoto", class: "area-panel-image" %>
    <% end %>
  </div>
  <div class="area-panel-item">
  <span>北海道</span>
    <%= link_to controller: "pages", action: "search", q: { address_cont: "北海道"} do %>
      <%= image_tag "https://images.unsplash.com/photo-1598176433730-2aca0907a717?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80", alt: "search_hokkaido", class: "area-panel-image" %>
    <% end %>
  </div>
  <div class="area-panel-item">
  <span>沖縄</span>
    <%= link_to controller: "pages", action: "search", q: { address_cont: "沖縄"} do %>
    <%= image_tag "https://images.unsplash.com/photo-1610971250019-f677bc1300be?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80", alt: "search_okinawa", class: "area-panel-image" %>
    <% end %>
  </div>
</div>

app/views/pages/search.html.erb
<div class="search-container">
  <h2>検索結果 <%= @count %>件</h2>
  <div class="search-results">
    <% @results.each do |hotel| %>
      <div class="content">
        <%= link_to hotel_path(hotel) do %>
          <%= image_tag hotel.image %>
          <p class="room-name"><%= hotel.room_name %></p>
          <p><%= hotel.address %></p>
          <p>1泊1人 <%= hotel.price %> 円</p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul style="margin-bottom: 20px; padding: 0 0 0 10px;">
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>